# Generated by Django 4.0.6 on 2022-07-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0002_citizen_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='submission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='mycity.citizen'),
        ),
    ]
