# Generated by Django 4.0.6 on 2022-07-31 09:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0003_alter_citizen_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='rght',
            field=models.PositiveIntegerField(default=400, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizen',
            name='submission',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='mycity.citizen'),
        ),
    ]
