# Generated by Django 4.0.6 on 2022-07-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0004_citizen_level_citizen_lft_citizen_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='submission',
            new_name='parent',
        ),
    ]
