# Generated by Django 4.0.6 on 2022-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0012_alter_citizen_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='submission',
            new_name='boss',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='role',
            field=models.CharField(choices=[('Pr', 'Князь'), ('Merch', 'Купец'), ('Serf', 'Холоп')], max_length=20),
        ),
    ]
