# Generated by Django 4.0.6 on 2022-07-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0013_rename_submission_citizen_boss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='boss',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'self'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citizen', to='mycity.citizen'),
        ),
    ]
