# Generated by Django 4.0.6 on 2022-07-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0014_alter_citizen_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='boss',
            field=models.ForeignKey(limit_choices_to={'role': 'self'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='mycity.citizen'),
        ),
    ]
