# Generated by Django 4.0.6 on 2022-07-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0015_alter_citizen_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mycity.citizen'),
        ),
    ]
