# Generated by Django 4.0.6 on 2022-07-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
